<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-23T12:02:03 IST" name="Default suite" finished-at="2022-09-23T12:02:10 IST" duration-ms="7608">
    <groups>
    </groups>
    <test started-at="2022-09-23T12:02:03 IST" name="Default test" finished-at="2022-09-23T12:02:10 IST" duration-ms="7608">
      <class name="com.citi.test.LoginUITest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.citi.test.LoginUITest@4686afc2]" started-at="2022-09-23T12:02:02 IST" name="init" finished-at="2022-09-23T12:02:03 IST" duration-ms="396" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.citi.test.LoginUITest@4686afc2]" started-at="2022-09-23T12:02:03 IST" name="setup" finished-at="2022-09-23T12:02:10 IST" duration-ms="6748" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ch]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.citi.test.LoginUITest.validateTitleTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateTitleTest()[pri:0, instance:com.citi.test.LoginUITest@4686afc2]" started-at="2022-09-23T12:02:10 IST" name="validateTitleTest" finished-at="2022-09-23T12:02:10 IST" duration-ms="53" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OpenEMR Login] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OpenEMR Login] but found [Google]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.citi.test.LoginUITest.validateTitleTest(LoginUITest.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitleTest -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.citi.test.LoginUITest@4686afc2]" started-at="2022-09-23T12:02:10 IST" name="teardown" finished-at="2022-09-23T12:02:10 IST" duration-ms="765" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateTitleTest status=FAILURE method=LoginUITest.validateTitleTest()[pri:0, instance:com.citi.test.LoginUITest@4686afc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="end()[pri:0, instance:com.citi.test.LoginUITest@4686afc2]" started-at="2022-09-23T12:02:10 IST" name="end" finished-at="2022-09-23T12:02:11 IST" duration-ms="647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.citi.test.LoginUITest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
